version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: friday
    allow:
      - dependency-type: all
    groups:
      ruby-deps:
        patterns: [ "*" ]