source 'https://rubygems.org'
gem 'gauge-ruby'
gem 'test-unit'
gem 'selenium-webdriver', '~> 2.53'
gem 'childprocess'
gem 'rest-client'
gem 'os'
gem 'rake'
gem 'sys-proctable', '< 1.1.4'
gem 'ffi', '< 1.9.18'
gem 'pry'
gem 'owasp_zap'
gem 'site_prism'
gem 'json_builder'
gem 'deep_merge'
gem 'roar'
gem 'multi_json'
