source 'https://rubygems.org'
gem 'gauge-ruby'
gem 'test-unit'
gem 'selenium-webdriver'
gem 'childprocess'
gem 'rest-client'
gem 'os'
gem 'rake'
gem 'sys-proctable'
gem 'ffi', '< 1.9.18'
gem 'pry'
gem 'owasp_zap'
gem 'site_prism', '3.0.3'
gem 'json_builder'
gem 'deep_merge'
gem 'roar'
gem 'multi_json'
gem 'ladle'
gem 'pry-coolline'
gem 'clipboard', '~> 1.3', '>= 1.3.3'
