# Configuration for https://mise.jdx.dev/ as an alternative to asdf, jabba, sdkman, rvm, nvm etc
[settings]
ruby.compile = false

[tools]
"java" = "temurin-25"
"ruby" = "4.0"
"aqua:getgauge/gauge" = { version = "1", postinstall = "gauge install" }

"chromedriver" = { version = "latest", os = ["linux", "macos"] } # plugin not working on Windows with pwsh right now :(
"github:mozilla/geckodriver" = { version = "latest", os = ["linux", "macos"] }

"jq" = "latest"
"regctl" = "latest"

[tasks]
"prepare:gocd-clean" = { run = "cd ../gocd && ./gradlew clean && cd ../go-plugins && ./gradlew clean" }
"prepare:test-clean" = { run = "cd ../ruby-functional-tests && bundle install && bundle exec rake clean_test" }

"prepare:gocd" = {
    wait_for = "prepare:gocd-clean",
    run = "cd ../gocd && ./gradlew installers:agentGenericZip installers:serverGenericZip installers:versionFile publishToMavenLocal"
}
"prepare:go-plugins" = {
    wait_for = ["prepare:gocd-clean", "prepare:gocd"],
    run = "cd ../go-plugins && ./gradlew assemble copyJarsToOnePlace -PgoVersion=$(jq '.go_full_version' -r ../gocd/installers/target/distributions/meta/version.json)"
}
"prepare:test" = {
    depends = ["prepare:gocd", "prepare:go-plugins"],
    wait_for = "prepare:test-clean",
    run = "cd ../ruby-functional-tests && bundle exec rake GO_VERSION=$(jq '.go_version' -r ../gocd/installers/target/distributions/meta/version.json) prepare"
}

"kill" = { run = "cd ../ruby-functional-tests && bundle exec rake kill" }
"prepare" = {
    depends = ["prepare:gocd", "prepare:go-plugins", "prepare:test"],
    wait_for = ["prepare:test-clean", "kill"]
}
"clean" = {
    depends = ["prepare:gocd-clean", "prepare:test-clean", "kill", "prepare"],
}

"test" = { run = "cd ../ruby-functional-tests && bundle exec rake GO_VERSION=$(jq '.go_version' -r ../gocd/installers/target/distributions/meta/version.json) test" }
