# #########################GO-LICENSE-START################################
# Copyright 2016 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# #########################GO-LICENSE-END##################################

# Test Rakefile to be checked in to any SCM material repostitory used in test

task :wait_for_stopjob_file do
  until File.exist?("../../../stopjob")
    sleep 1
  end
  p "Exiting waiting loop as the stop job file created"
end

task :wait_and_fail do
  until File.exist?("../../../failjob")
    sleep 1
  end
  fail("Intentionally fail the job")
end

task :wait_or_fail do
  until File.exist?("../../../failjob") || File.exist?("../../../stopjob")
    sleep 1
  end
  fail("Intentionally fail the job") if File.exist?("../../../failjob")
end

task :wait_forever do
  until File.exist?("../../../neverexists")
    sleep 1
  end
end
